<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.dcits.demo.OpenChrome" tests="7" time="14.571" ignored="2" failures="2" timestamp="25 八月 2019 08:10:56 GMT" skipped="0" hostname="HELLOWORLD" errors="0">
  <testcase name="register" time="0.720" classname="com.dcits.demo.OpenChrome">
    <failure type="java.lang.AssertionError" message="expected [注册成功!] but found [账号已存在]">
      <![CDATA[java.lang.AssertionError: expected [注册成功!] but found [账号已存在]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.dcits.demo.OpenChrome.register(OpenChrome.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- register -->
  <testcase name="loginFromExcel" time="0.644" classname="com.dcits.demo.OpenChrome">
    <failure type="java.lang.AssertionError" message="expected [null] but found [账号或密码错误]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [账号或密码错误]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:130)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.dcits.demo.OpenChrome.loginFromExcel(OpenChrome.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- loginFromExcel -->
  <testcase name="loginFromExcel" time="2.633" classname="com.dcits.demo.OpenChrome"/>
  <testcase name="login" time="2.604" classname="com.dcits.demo.OpenChrome"/>
  <testcase name="loginFromExcel" time="2.636" classname="com.dcits.demo.OpenChrome"/>
  <testcase name="loginFromExcel" time="2.628" classname="com.dcits.demo.OpenChrome"/>
  <testcase name="repeatregister" time="2.706" classname="com.dcits.demo.OpenChrome"/>
  <testcase name="repeat2register" classname="com.dcits.demo.OpenChrome">
    <skipped/>
  </testcase> <!-- repeat2register -->
  <testcase name="loginError" classname="com.dcits.demo.OpenChrome">
    <skipped/>
  </testcase> <!-- loginError -->
</testsuite> <!-- com.dcits.demo.OpenChrome -->
